### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by john-colgrave** [ansible-community/ansible.content_builder#27]
##### SUMMARY

There are a couple of missing dependencies, at least when the content_builder is used with a type of module_openapi:
jsonschema
yaml

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible.content_builder

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible-env/lib64/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/ansible-env/bin/ansible
  python version = 3.9.14 (main, Sep 21 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] (/root/ansible-env/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT

CentOS Stream release 9

##### STEPS TO REPRODUCE

Install ansible.content_builder per the README and then try to run it to generate a module from a swagger file.

```yaml
(ansible-env) [root@jc-ansible-centos91 content_builder_test]# cat build.yaml
---
- hosts: localhost
  gather_facts: yes
  roles:
    - ansible.content_builder.run
(ansible-env) [root@jc-ansible-centos91 content_builder_test]# cat MANIFEST.yaml
---
collection:
  path: /root/content_builder_test/output
  namespace: john_colgrave
  name: testos
plugins:
  - type: module_openapi
    name: testos_plugin
    module_version: 1.0.0
    rm_swagger_json: /root/content_builder_test/petstore.json
    api_object_path: /pets
    resource: testos_resource
    unique_key: ""
    author: "John Colgrave"
```

##### EXPECTED RESULTS

A module to be generated.

##### ACTUAL RESULTS

I got the error below about the jsonschema library. Once I had installed it into my python virtual environment and made sure that ansible-playbook was using the virtual environment, the problem went away.

I later saw a similar issue with oyaml and I had to install that too.

```paste below
(ansible-env) [root@jc-ansible-centos91 content_builder_test]# ansible-playbook build.yaml -e manifest_file=MANIFEST.yaml
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] *******************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************
ok: [localhost]

TASK [ansible.content_builder.run : Validate task input against defined schema] ****************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleError: Failed to import the required Python library (jsonschema) on jc-ansible-centos91.fyre.ibm.com's Python /usr/bin/python3.9. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (jsonschema) on jc-ansible-centos91.fyre.ibm.com's Python /usr/bin/python3.9. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

PLAY RECAP *************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
