### ISSUE TITLE
UnboundLocalError from doc_generator.py

### ISSUE THREAD

**Issue by john-colgrave** [ansible-community/ansible.content_builder#29]
##### SUMMARY

When trying to generate a module of type openapi, I get an error from doc_generator.py

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

content_builder

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible-env/lib64/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/ansible-env/bin/ansible
  python version = 3.9.14 (main, Sep 21 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] (/root/ansible-env/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT

CentOS Stream 9

##### STEPS TO REPRODUCE

Run the content_builder to generate a module of type openapi.

```yaml
(ansible-env) [root@jc-ansible-centos91 content_builder_test]# cat build.yaml
---
- hosts: localhost
  gather_facts: yes
  roles:
    - ansible.content_builder.run
(ansible-env) [root@jc-ansible-centos91 content_builder_test]# cat MANIFEST.yaml
---
collection:
  path: /root/content_builder_test/output
  namespace: john_colgrave
  name: testos
plugins:
  - type: module_openapi
    name: testos_plugin
    module_version: 1.0.0
    rm_swagger_json: /root/content_builder_test/petstore.json
    api_object_path: /pets
    resource: testos_resource
    unique_key: ""
    author: "John Colgrave"
```

##### ACTUAL RESULTS

I get a fatal error.

```paste below
See attached file test_output.txt
```
[test_output.txt](https://github.com/ansible-community/ansible.content_builder/files/10164907/test_output.txt)
